# Configuration file for camera, radar, and lidar
use:
    camera: 
        enabled: true
        config: './camera_config.yaml'
    lidar: 
        enabled: true
        correction_csv: './Pandar40P_correction.csv'
        ip: '192.168.1.201'
    radar: 
        enabled: true
        cfg_file: './radar_config.cfg'

show:
    rviz: true
    image_view: false

record:
    enabled: true
    output_dir: '/ssd/rosbags' # Use full path (e.g. /home/user/Documents not ~/Documents)
    raw_camera: false